name-template: "v$PREVIOUS_TAG-hotfix"
tag-template: "v$PREVIOUS_TAG-hotfix"
categories:
  - title: "💣 Breaking Change"
    labels:
      - "💣 Breaking change"
  - title: "🚀 Feature"
    labels:
      - "🚀 Feature"
  - title: "🐛 Bugfix"
    labels:
      - "🐛 Bugfix"
  - title: "🔥 Hotfix"
    labels:
      - "🔥 Hotfix"
  - title: "📚 Documentation"
    labels:
      - "📚 Documentation"
  - title: "🏗️ Refactor"
    labels:
      - "🏗️ Refactor"
  - title: "🧪 Test"
    labels:
      - "🧪 Test"
  - title: "🚨 Security"
    labels:
      - "🚨 Security"
  - title: "☁️ CI"
    labels:
      - "☁️ CI"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "💣 Breaking change"
  minor:
    labels:
      - "🚀 Feature"
  patch:
    labels:
      - "🐛 Bugfix"
      - "🔥 Hotfix"
      - "📚 Documentation"
      - "🏗️ Refactor"
      - "🧪 Test"
      - "🚨 Security"
      - "☁️ CI"
  default: patch
template: |
  $CHANGES
