name: Deploy

on:
  release:
    types: [published, released]
  push:
    branches:
      - main
      - prod

jobs:
  prepare:
    name: Prepare
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/prepare.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Build
        id: build
        run: |
          echo "build"

  homolog:
    name: Homolog
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.homolog == 'true'
    steps:
      - name: Deploy Homolog
        id: deploy-homolog
        run: |
          echo "deploy homolog ${{ needs.prepare.outputs.tag }}"

  sandbox:
    name: Sandbox
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.sandbox == 'true'
    steps:
      - name: Deploy Sandbox
        id: deploy-sandbox
        run: |
          echo "deploy sandbox ${{ needs.prepare.outputs.tag }}"

  production:
    name: Production
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.production == 'true'
    steps:
      - name: Deploy Prod
        id: deploy-prod
        run: |
          echo "deploy prod ${{ needs.prepare.outputs.tag }}"

  update-prod:
    name: Update prod branch
    runs-on: ubuntu-latest
    needs: [prepare, build, production]
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge prod back to main
        run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff prod -m "auto merge prod back to main"
          git push

  update-main:
    name: Update main branch
    runs-on: ubuntu-latest
    needs: [prepare, build, production]
    if: ${{ github.ref_name == 'prod' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge prod back to main
        run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff origin/prod -m "auto merge prod back to main"
          git push
