name: Deploy

on:
  release:
    types: [published, released]
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      env:
        type: choice
        default: Homolog
        description: Environment
        options: 
          - Homolog
          - Sandbox
          - Prod

jobs:
  prepare:
    name: Prepare
    if: |
      github.actor != 'dependabot[bot]' && 
      github.event.pull_request.user.login != 'github-actions[bot]' && 
      (
        (github.event.action == 'published' && github.event.release.prerelease) ||
        (github.event.action == 'released' && github.event.release.prerelease == false) ||
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'pull_request'
      )
    uses: ./.github/workflows/prepare.yml
    with:
      env: ${{ github.event.inputs.env }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Build
        id: build
        run: |
          echo "build"

  homolog:
    name: Homolog
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.homolog == 'true'
    steps:
      - name: Deploy Homolog
        id: deploy-homolog
        run: |
          echo "deploy homolog ${{ needs.prepare.outputs.tag }}"

  sandbox:
    name: Sandbox
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.sandbox == 'true'
    steps:
      - name: Deploy Sandbox
        id: deploy-sandbox
        run: |
          echo "deploy sandbox ${{ needs.prepare.outputs.tag }}"

  production:
    name: Production
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.production == 'true'
    steps:
      - name: Deploy Prod
        id: deploy-prod
        run: |
          echo "deploy prod ${{ needs.prepare.outputs.tag }}"

  update-prod:
    name: Update prod branch
    runs-on: ubuntu-latest
    needs: [prepare, build, production]
    if: ${{ github.event.action == 'released' }}
    steps:
      - uses: actions/checkout@v3
      - name: Create PR to update prod branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          gh pr create --title "[${{ needs.prepare.outputs.tag }}] Production Deployment Merge" --body "Merges main branch to prod after a production deployment" --base prod --head main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-main:
    name: Update main branch
    runs-on: ubuntu-latest
    needs: [prepare, build, production]
    if: ${{ github.ref_name == 'prod' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create PR to update main branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          gh pr create --title "Hotfix Update" --body "Merges prod hotfix to main branch" --base main --head prod --label "🔥 Hotfix"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
