name: Deploy

on:
  release:
    types: [published, released]
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  prepare:
    name: Prepare
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./prepare.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - name: Set vars
        id: set-vars
        run: |
          echo "build"

  homolog:
    name: Homolog
    runs-on: ubuntu-latest
    needs: [ prepare, build ]
    if: needs.prepare.outputs.homolog == 'true'
    steps:
      - name: Set vars
        id: set-vars
        run: |
          echo "deploy homolog ${{ needs.prepare.outputs.tag }}"

  sandbox:
    name: Sandbox
    runs-on: ubuntu-latest
    needs: [ prepare, build ]
    if: needs.prepare.outputs.sandbox == 'true'
    steps:
      - name: Set vars
        id: set-vars
        run: |
          echo "deploy homolog ${{ needs.prepare.outputs.tag }}"

  production:
    name: Production
    runs-on: ubuntu-latest
    needs: [ prepare, build, sandbox ]
    if: needs.prepare.outputs.production == 'true'
    steps:
      - name: Set vars
        id: set-vars
        run: |
          echo "deploy homolog ${{ needs.prepare.outputs.tag }}"
