name: Deploy

on:
  release:
    types: [published, released]
  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/prepare.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - name: Set vars
        id: set-vars
        run: |
          echo "build"

  homolog:
    name: Homolog
    runs-on: ubuntu-latest
    needs: [ prepare, build ]
    if: needs.prepare.outputs.homolog == 'true'
    steps:
      - name: Set vars
        id: set-vars
        run: |
          echo "deploy homolog ${{ needs.prepare.outputs.tag }}"

  sandbox:
    name: Sandbox
    runs-on: ubuntu-latest
    needs: [ prepare, build ]
    if: needs.prepare.outputs.sandbox == 'true'
    steps:
      - name: Set vars
        id: set-vars
        run: |
          echo "deploy homolog ${{ needs.prepare.outputs.tag }}"

  production:
    name: Production
    runs-on: ubuntu-latest
    needs: [ prepare, build ]
    if: needs.prepare.outputs.production == 'true'
    steps:
      - name: Set vars
        id: set-vars
        run: |
          echo "deploy homolog ${{ needs.prepare.outputs.tag }}"

  auto-merge-prod:
    name: Auto merge prod back to main
    runs-on: ubuntu-latest
    needs: [ prepare, build, production ]
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff prod -m "auto merge prod back to main"
          git push
