name: Deploy

on:
  release:
    types: [published, released]
  push:
    branches:
      - main
      - prod

jobs:
  prepare:
    name: Prepare
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/prepare.yml

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Build
        id: build
        run: |
          echo "build"

  homolog:
    name: Homolog
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.homolog == 'true'
    steps:
      - name: Deploy Homolog
        id: deploy-homolog
        run: |
          echo "deploy homolog ${{ needs.prepare.outputs.tag }}"

  sandbox:
    name: Sandbox
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.sandbox == 'true'
    steps:
      - name: Deploy Sandbox
        id: deploy-sandbox
        run: |
          echo "deploy sandbox ${{ needs.prepare.outputs.tag }}"

  production:
    name: Production
    runs-on: ubuntu-latest
    needs: [prepare, build]
    if: needs.prepare.outputs.production == 'true'
    steps:
      - name: Deploy Prod
        id: deploy-prod
        run: |
          echo "deploy prod ${{ needs.prepare.outputs.tag }}"

  update-prod:
    name: Update prod branch
    runs-on: ubuntu-latest
    needs: [prepare, build, production]
    if: ${{ github.event.action == 'released' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge prod back to main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --unshallow
          git checkout prod
          git pull
          git merge origin/main --ff-only
          git push

  update-main:
    name: Update main branch
    runs-on: ubuntu-latest
    needs: [prepare, build, production]
    if: ${{ github.ref_name == 'prod' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Hotfix update to main
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: hotfix
          title: "[Hotfix Update] Update main branch with hotfix"
          body: |
            Update report
            - Updates main branch after a hotfix is merged to prod branch directly
            - Auto-generated
          labels: |
            🔥 Hotfix
