name: Auto Assign

on: pull_request

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.3
        with:
          configuration-path: ".github/auto-assign.yml"
