---
  name: Deploy - Prepare
  
  on:
    workflow_call:
      inputs:
        env:
          description: "Environment to deploy by workflow dispatch"
          type: string
        isHotfix:
          description: "Is hotfix deploy"
          type: boolean
      outputs:
        homolog:
          description: "Boolean to activate homolog build/deploy"
          value: ${{ jobs.prepare.outputs.homolog }}
        sandbox:
          description: "Boolean to activate sandbox build/deploy"
          value: ${{ jobs.prepare.outputs.sandbox }}
        production:
          description: "Boolean to activate production build/deploy"
          value: ${{ jobs.prepare.outputs.production }}
        tag:
          description: "TAG"
          value: ${{ jobs.prepare.outputs.tag }}
  
  jobs:
    prepare:
      name: Prepare
      runs-on: ubuntu-latest
      outputs:
        homolog: ${{ steps.set-vars.outputs.homolog }}
        sandbox: ${{ steps.set-vars.outputs.sandbox }}
        production: ${{ steps.set-vars.outputs.production }}
        tag: ${{ steps.set-vars.outputs.tag }}
      steps:
        - uses: release-drafter/release-drafter@v5
          id: draft-release
          if: ${{ inputs.isHotfix }}
          with:
            publish: true
            prerelease: false
            commitish: refs/heads/develop
            config-name: release-drafter-hotfix.yml
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Set vars
          id: set-vars
          run: |
            homolog="false"
            sandbox="false"
            production="false"
            tag=${{ github.ref_name }}
            sha=${{ github.sha }}
            key=${sha::7}-${{ github.run_id }}-${{ github.run_attempt }}

            if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
              tag=${{ inputs.env }}-$short_sha
            fi
  
            if [[ ("${{ github.event_name }}" != "workflow_dispatch" && "${{ github.ref_name }}" == "develop") || "${{ inputs.env }}" == "homolog" ]]; then
              homolog="true"
              
              tag=$tag-$key
            fi
  
            if [[ "${{ github.event.action }}" == "published" || "${{ inputs.env }}" == "sandbox" ]]; then
              sandbox="true"

              tag=$tag-$key
            fi
  
            if [[ ("${{ github.event.action }}" == "released" && "${{ github.event.release.prerelease }}" == "false") || "${{ github.ref_name }}" == "main" ]]; then
              production="true"
            fi

            if [[ "${{ inputs.isHotfix }}" == "true" ]]; then
              production="true"
              
              tag=${{ steps.draft-release.outputs.tag_name }}
            fi
  
            echo "homolog=$homolog" >> $GITHUB_OUTPUT
            echo "sandbox=$sandbox" >> $GITHUB_OUTPUT
            echo "production=$production" >> $GITHUB_OUTPUT
            echo "tag=$tag" >> $GITHUB_OUTPUT
  
            echo "Homolog: $homolog"
            echo "Sandbox: $sandbox"
            echo "Production: $production"
            echo "Tag: $tag"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
