name: Release Drafter
on:
  pull_request:
    types:
      - closed

permissions:
  contents: read

jobs:
  update_release_draft:
    if: github.event.pull_request.merged == true && (github.base_ref == 'main' || github.base_ref == 'develop')
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: github.base_ref == 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
