name: Release Drafter
on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - closed

permissions:
  contents: read

jobs:
  draft-release:
    if: github.ref_name == 'develop' || (github.event.pull_request.merged == true && (github.base_ref == 'main' || github.base_ref == 'develop'))
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $github.base_ref
      - uses: release-drafter/release-drafter@v5
        with:
          publish: ${{ github.base_ref == 'main' }}
          prerelease: ${{ github.base_ref == 'develop' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
