name: Release Drafter
on:
  pull_request:
    types:
      - closed

permissions:
  contents: read

jobs:
  draft-release:
    if: github.event.pull_request.merged == true && github.base_ref == 'develop' && github.head_ref != 'auto-hotfix'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          prerelease: true
          commitish: refs/heads/develop
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
