name: Release Drafter
on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  draft-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: o-mago/release-drafter@add-latest
        with:
          publish: true
          commitish: refs/heads/develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
